services:
  postgres:
    image: postgres:18
    container_name: ${PROJECT}-postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${VOLUME_PATH:-.data}/postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  flyway:
    image: flyway/flyway:12.0.1
    profiles:
      - tools
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_SCHEMAS: ${FLYWAY_SCHEMAS}
      FLYWAY_DEFAULT_SCHEMA: ${FLYWAY_DEFAULT_SCHEMA}
    volumes:
      - ./.infra/database/migration:/flyway/sql:ro
      - ./.infra/database/flyway.conf:/flyway/conf/flyway.conf:ro
