; Migration settings
flyway.locations=filesystem:/flyway/sql
flyway.sqlMigrationPrefix=v
flyway.sqlMigrationSeparator=__
flyway.sqlMigrationSuffixes=.sql

; Schema history settings
flyway.table=flyway_schema_history

; Baseline settings
flyway.baselineOnMigrate=true
flyway.baselineDescription=Initial baseline
flyway.baselineVersion=0.0.0

; Schema settings
flyway.createSchemas=true

; Safety settings
flyway.cleanDisabled=true
